inherits = "ayu_dark"

# Syntax highlightning
"variable.parameter" = { fg = "pink", modifiers = ["italic"] }

"keyword" = "blue"
"keyword.control" = "orange"

"function.builtin" = { fg = "yellow", modifiers = ["italic"] }

"constructor" = "pink"

[palette]
cyan = "#76c2bf"
green = "#96a13a"
magenta = "#d2a6ff"
pink = "#ff5c95"
red = "#cc3f0c"
